spring:
  application:
    name: account-service

domain:
  account:
    savings:
      maintenanceFee: 0.0
      maxMonthlyMovements: 10
      maxPerCustomer: 1
    current:
      maintenanceFee: 12.0
      maxMonthlyMovements: -1
      business:
        allowMultiple: true
        minHolders: 1
        allowAuthorizedSigners: true
    fixedTerm:
      maintenanceFee: 0.0
      allowedMovementDay: 15
      maxPerCustomer: -1
