spring:
  application:
    name: card-service

domain:
  card:
    supportedTypes: [PERSONAL, ENTERPRISE]
    limits:
      defaultCreditLimit: 5000
    spending:
      enableCharges: true

queries:
  allowBalanceInquiry: true
